apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: todoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-headless
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "localhost"]
            timeoutSeconds: 20
            failureThreshold: 10
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: a
            - name: MYSQL_DATABASE
              value: todo-list
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-init-scripts
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-init-scripts
          configMap:
            name: mysql-init-scripts
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: local-path 


