apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: todoapp
spec:
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None # Headless Service
  selector:
    app: mysql
