---
- hosts: kubernetes-worker-nodes
  become: yes
  tasks:    
    - name: Extract kubeadm join command
      shell: tail -n 2 /tmp/init_output.txt
      register: join_command

    - name: Execute kubeadm join command
      shell: "{{ join_command.stdout }}"
