apiVersion: v1
kind: ConfigMap
metadata:
  name: task-service-config
  namespace: todoapp
data:
  DB_DSN: "root:a@tcp(mysql-headless:3306)/todo-auth?charset=utf8mb4&parseTime=True&loc=Local"
  GIN_PORT: "3300"
  GRPC_AUTH_ADDRESS: "auth-service:3101"

