apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  labels:
    app: task-service
  namespace: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      containers:
        - name: task-service
          image: minhbui1/task-svc
          ports:
            - containerPort: 3300
          env:
            - name: DB_DSN
              valueFrom:
                configMapKeyRef:
                  name: task-service-config
                  key: DB_DSN
            - name: GIN_PORT
              valueFrom:
                configMapKeyRef:
                  name: task-service-config
                  key: GIN_PORT
            - name: GRPC_AUTH_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: task-service-config
                  key: GRPC_AUTH_ADDRESS

