apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: todoapp
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: tyk-gateway
          image: tykio/tyk-gateway:v3.1.0
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tyk-config
              mountPath: /opt/tyk-gateway/tyk.conf
              subPath: tyk.conf
            - name: tyk-apps
              mountPath: /opt/tyk-gateway/apps
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
      volumes:
        - name: tyk-config
          configMap:
            name: tyk-config
        - name: tyk-apps
          configMap:
            name: tyk-apps
