apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: todoapp
spec:
  ports:
    - name: gin
      port: 3200
      targetPort: 3200
    - name: grpc
      port: 3201
      targetPort: 3201
  selector:
    app: user-service
