apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
  namespace: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: minhbui1/auth-svc
          ports:
            - containerPort: 3100
            - containerPort: 3101
          env:
            - name: DB_DSN
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: DB_DSN
            - name: GIN_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: GIN_PORT
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: GRPC_PORT
            - name: GRPC_USER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: GRPC_USER_ADDRESS
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: JWT_SECRET
