apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: todoapp
spec:
  ports:
    - name: gin
      port: 3100
      targetPort: 3100
    - name: grpc
      port: 3101
      targetPort: 3101
  selector:
    app: auth-service
